id: P06BBBA11
initial_creation_type: input
source_metadata:
  title: Guru Padmasambhava
  language: en
  description: 'Prayers to the Precious Guru Padmasambhava or Padmākara (padma ''byung
    gnas), the "Lotus-Born", who is credited with establishing Buddhism in Tibet:'
  volume:
    5ba8929f5c7c4a76bf9d03e5fa8a031b:
      title: A Synopsis of Guru Padmasambhava’s Life
      parent: Alak Zenkar Pema Ngödrup Rolwe Dorje
    fa3573b99b32434186392b68519d595c:
      title: A Prayer of Aspiration for the Copper-Coloured Mountain of Glory
      parent: Dudjom Rinpoche
    8d6b8d3db88a4daa9f10476b2da6bbde:
      title: 'Pearl Droplets of Blessings: A Prayer to the Guru Who Embodies All'
      parent: Chokgyur Dechen Lingpa
    8cdaef913cfb4534ac2e3c80494da191:
      title: The Prayer Which Removes All Obstacles from the Path (Barché Lamsel)
      parent: Chokgyur Dechen Lingpa
    58cdbf594db4488c8a1e2243c3458cfb:
      title: The Prayer in Six Vajra Lines
      parent: Chokgyur Dechen Lingpa
    845afe9521ff4dd9a2eb8bdd9b0c6627:
      title: The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma)
      parent: Chokgyur Dechen Lingpa
    e5acc737804d4a4dab490040138a5926:
      title: 'The Prayer to Guru Rinpoche that Spontaneously Fulfils All Wishes (Sampa
        Lhundrupma) from The Guru’s Heart Practice: The Wish-Fulfilling Jewel'
      parent: Chokgyur Dechen Lingpa
    7a9733e5096f46c5adbe171d68db422d:
      title: The Testament Prayer to Orgyen Rinpoche
      parent: Chokgyur Dechen Lingpa
    54561d5934f54ee886c9eadc0075c9cc:
      title: 'The Wish-Fulfilling Tree: The Life Story of the Master of Uḍḍiyāna
        as found in Padmasambhava’s Sevenfold Cycle of Profundity'
      parent: Chokgyur Dechen Lingpa
    4fff258676a449ddbc3ea1b0bd85bc7e:
      title: Threefold Aspiration for Rebirth in Zangdok Palri
      parent: Chokgyur Dechen Lingpa
    f5da3304612b485abde9d5c6fe67997b:
      title: 'A Garland of Vajra Words: A Prayer to the Guru'
      parent: Dilgo Khyentse Rinpoche
    60e88cac3e5540d9859a55cee9617739:
      title: 'All Wishes Swiftly Fulfilled: A Prayer to the Mahāguru of Uḍḍiyāna in
        Eight Chapters'
      parent: Dilgo Khyentse Rinpoche
    1297c73e5e474dad9bc896e9bb49b862:
      title: The Prayer to Swiftly Fulfil All Wishes
      parent: Dilgo Khyentse Rinpoche
    ad904b95d5be409fab9d89926789da4c:
      title: 'The Precious Jewel Essence: A Prayer of the Four Dharmas'
      parent: Dilgo Khyentse Rinpoche
    976e352ca0db46268f786ba9d4b7012d:
      title: A Very Brief Prayer for Clearing Obstacles from the Path (Barche Lamsel)
      parent: Do Khyentse
    093833c0e1fe47998d2edfaccab2fe51:
      title: 'The Lightning Bolt of Compassion: A Short Prayer that Spontaneously
        Fulfils All Wishes (Sampa Lhundrupma)'
      parent: Do Khyentse
    0462328ce8eb490fa1a5ffdb62be9f96:
      title: Prayer to Padmasambhava, Longchenpa and Jigme Lingpa
      parent: Dodrupchen Jigme Tenpe Nyima
    0671762f753c49519bb22e69915d7543:
      title: 'The Adamantine Magical Wheel: Invoking the Profound Pledge of Padmākara,
        the Glorious Victor, to Avert the Final War'
      parent: Dodrupchen Jigme Tenpe Nyima
    31a36f465f4d4386a858e7dbe80499b9:
      title: The Prayer to Guru Rinpoche for Attainments
      parent: Dodrupchen Jigme Trinle Özer
    e573562128c84cbc8b3a61bc125a3dae:
      title: A Prayer to Padmasambhava
      parent: Dudjom Lingpa
    b780ecabdd0b4bc1a49f9cadc3fd4807:
      title: 'A Joyful Chariot for the Fortunate: An Aspiration to Travel to the Copper-Coloured
        Mountain of Glory'
      parent: Dudjom Rinpoche
    de8f6e35a1ac444b82bdd8d334ff3c59:
      title: A Short Prayer to the Abbot, the Master and the King
      parent: Dudjom Rinpoche
    f2770cc727c749ce942e29e5f40d36fa:
      title: 'Drumbeat of the Deathless Vajra: A Fervent Invocation and Prayer'
      parent: Dudjom Rinpoche
    9afcb81e22404687a6f5b540ec1ba123:
      title: The Ornament of Padmasambhava’s Enlightened Vision
      parent: Dudjom Rinpoche
    b1c35dad35d4408e9e28cb78b949e2b6:
      title: The Prayer to Guru Rinpoche that Swiftly Removes Obstacles and Fulfills
        All Wishes
      parent: Dudjom Rinpoche
    11ea3516634b483491f43942f1d7e440:
      title: A Prayer to the Precious Guru from Uḍḍiyāna That Spontaneously Fulfils
        All Wishes
      parent: Dzongter Kunzang Nyima
    68983d44d5c2487fbde4930381343b01:
      title: 'Cloud Banks of Blessings: A Prayer to Guru Padmasambhava'
      parent: Fifth Dalai Lama
    792c78809168414fa25d80b54e8bf6b1:
      title: A Yearning Song of Prayer to Invoke the Wisdom Mind of the Compassionate
        Teacher Padmasambhava
      parent: Fourteenth Dalai Lama
    32b2ad15b4ab40de86a755943a72bbd9:
      title: A Prayer to Guru Rinpoche That Spontaneously Fulfils All Wishes (from
        the Extremely Secret Assembly of Sugatas)
      parent: Garwang Chökyi Gyaltsen
    d306fac98a1f4961b57d1672dec6f962:
      title: Prayer to Orgyen Rinpoche Invoking His Wisdom Mind
      parent: Gönpo Tseten Rinpoche
    80175724497d4774b5d595c30dbc6d00:
      title: The Prayer of the Tenth Days in Guru Rinpoche’s Life Story entitled ‘The
        Nucleus of Blessings’
      parent: Jamgön Kongtrul
    c6385e7144db4cdba51ddf83dc6db63f:
      title: A Heart Prayer to Orgyen Dorje Chang
      parent: Jamyang Khyentse Chökyi Lodrö
    e077953fbc214d568e1201a33c1fd3ea:
      title: A Prayer of Aspiration for the Mountain of Glory
      parent: Jamyang Khyentse Chökyi Lodrö
    f3142af6097b41268bddb49ce8bd8f7a:
      title: A Prayer to Orgyen Dorje Chang
      parent: Jamyang Khyentse Chökyi Lodrö
    cc66ddefbf004f34aec8e9a71b4306c9:
      title: A Yearning Plea to the Precious Guru
      parent: Jamyang Khyentse Chökyi Lodrö
    d17c6e055f074fd296cd91167ed74ae4:
      title: 'Cloud Banks of Blessings: A Prayer to Orgyen Rinpoche'
      parent: Jamyang Khyentse Chökyi Lodrö
    446f6236ffb84380a62a4bdf48f259eb:
      title: Prayer of the Wisdom Mind
      parent: Jamyang Khyentse Chökyi Lodrö
    e23178d5aec440beb8dd6c39ff2889ba:
      title: Spontaneous Fulfilment of Wishes
      parent: Jamyang Khyentse Chökyi Lodrö
    cdb629a93cf148dd88133836291c10d1:
      title: The Falling Elixir of Blessing
      parent: Jamyang Khyentse Chökyi Lodrö
    cad90a4c5a2d4bff9fa11674da3df9a5:
      title: 'The Fulfilment of Wishes and Aspirations: A Prayer to Ācārya Padmasambhava'
      parent: Jamyang Khyentse Chökyi Lodrö
    2aec48d72d19492fab1c1dcf9bbcfeb1:
      title: 'The Supreme Bestowal of Twofold Attainment: A Prayer to Orgyen Rinpoche,
        Embodiment of All Sources of Refuge'
      parent: Jamyang Khyentse Chökyi Lodrö
    25775df549844b79959314b6d7dead6d:
      title: 'The Swift Fulfilment of Aspirations: A Prayer to Glorious Orgyen, King
        of Dharma'
      parent: Jamyang Khyentse Chökyi Lodrö
    a588e5c0d1244c7fb808fe3eef8c9e0c:
      title: 'The Vajra Words Unveiled: A Commentary on the Düsum Sangyé Prayer to
        the Guru'
      parent: Jamyang Khyentse Chökyi Lodrö
    58229313c24044b1ae45697e86244cff:
      title: To Fulfil All Wishes
      parent: Jamyang Khyentse Chökyi Lodrö
    7a527cf9be0a43aaaf4e4f650fe67805:
      title: Turning Back the Misfortunes of the Age of Degeneration
      parent: Jamyang Khyentse Chökyi Lodrö
    61d1e1c0b78742768da28991871c0015:
      title: 'A Beautiful and Wondrous Udumbara Garland: A Supplication and Summary
        of the Chronicles of Padma, The Life and Liberation of the Precious Guru of
        Uḍḍiyāna'
      parent: Jamyang Khyentse Wangpo
    3b6a7da7b97e4fddaa574f26178395ab:
      title: A Brief Prayer to the Precious Master Padmākara for Swiftly Fulfilling
        Wishes
      parent: Jamyang Khyentse Wangpo
    d289a4a584864325a0156a246b104877:
      title: 'The Chariot of the Vidyādharas: An Aspiration Prayer for Travelling
        to the Realm of Lotus Light'
      parent: Jamyang Khyentse Wangpo
    e69037c938b14de180987ac7d3340c9e:
      title: The General Visualization for Prayers to Guru Rinpoche
      parent: Jamyang Khyentse Wangpo
    b5fdabba5c2c4627906ca718d6d8d8b2:
      title: 'The Heart of Blessings: A Brief Anthology of Prayers to Guru Rinpoche
        and the Twenty-Five Disciples, the King and Subjects'
      parent: Jamyang Khyentse Wangpo
    76a4a617073046d49516f0d46ab2dbaa:
      title: 'Turning Back Obstacles and Adverse Circumstances: A Prayer to Orgyen
        Rinpoche, Embodiment of All Sources of Refuge'
      parent: Jamyang Khyentse Wangpo
    15cb01120ccc4a15847f8efde8278310:
      title: 'Wish-Fulfilling Feast of Siddhis: An Aspiration Prayer to Orgyen Rinpoche,
        the Precious Master of Oddiyana'
      parent: Jamyang Khyentse Wangpo
    8c08bd79126f44c9ba26b35363ec6bed:
      title: A Prayer Invoking the Benefits of the Festival of the Tenth Day
      parent: Jigme Lingpa
    7bcce038ffe14577a84545e9df28bcf4:
      title: A Prayer of Devotion, to Make the Tears Fall
      parent: Jigme Lingpa
    f66fc67060c147ba8427ab91e7669dc4:
      title: Secret Path to the Mountain of Glory—A Prayer of Aspiration for the Copper-Coloured
        Mountain of Glory
      parent: Jigme Lingpa
    e025c88602d440f490e648933812aaf7:
      title: Training in the Pure Realms of the Three Kāyas
      parent: Jigme Lingpa
    a139cb1ae65f4e828de8f424c846cfaf:
      title: Prayer to Pema Tötreng Tsal
      parent: Khenchen Ngawang Palzang
    c209a1bf02a343c1be27471f39b22707:
      title: The Prayer that Swiftly Fulfils All Wishes (Sampa Nyur Drupma)
      parent: Longchen Rabjam
    9d86ce30acce46ecadf59d7162863154:
      title: Prayer to the Indian Mahāpaṇḍita Padmasambhava
      parent: Menlungpa Mikyö Dorje
    0b837eb0b10744088d560df545b9e6e8:
      title: A Plaintive Prayer to Guru Rinpoche
      parent: Minling Chung Rinpoche
    41c0deb922b14b1ab128bb2d2f8a7ced:
      title: A Brief Prayer for the Spontaneous Fulfilment of Aspirations
      parent: Mipham Rinpoche
    0be63e1c85a94fd1bf47116a7064a7cd:
      title: Recollecting the Deeds of The Tenth Days
      parent: Mipham Rinpoche
    335074d5426d420897540b2e62eecded:
      title: The Prayer which is the Source of All True Realization
      parent: Mipham Rinpoche
    c35994d6107d420d91aa1d0a5bb849b5:
      title: 'The Secret Path of Wisdom: A Prayer of Aspiration for the Mountain of
        Glory'
      parent: Mipham Rinpoche
    c6a668cc4fd941ac874530d66bf448a7:
      title: A Prayer Recalling the Life and Liberation of the Precious Master Padmasambhava
      parent: Nyang Ral Nyima Özer
    fbdeef52e16f4affb42a06c53eea6f0d:
      title: The Abbreviated Prayer in Seven Chapters
      parent: Nyang Ral Nyima Özer
    5cb28284d5544c0f80218dcee64c15cb:
      title: The Prayer to Orgyen Rinpoche that Invokes the Heart of his Wisdom Mind
      parent: Pawo Lerab Tsal
    e753b4113a1b44219a2a74c37d5a5721:
      title: An Extremely Concise Barché Lamsel—The Prayer for Clearing Obstacles
        from the Path
      parent: Rangrik Dorje
    2c9578a553e8405b874c492543a47937:
      title: An Extremely Concise Sampa Lhundrup—Prayer that Spontaneously Fulfils
        All Wishes
      parent: Rangrik Dorje
    fcb3750102114c7a817e6a7d4e47c440:
      title: The Seven Lines that Dispel All Obstacles and Enfold All Profundity
      parent: Rangrik Dorje
    0cc0142af5e24de48ac8efe7e960ee74:
      title: 'The Spontaneous Fulfilment of All Wishes: Invoking the Great Guru of
        Uḍḍiyāna'
      parent: Rangrik Dorje
    5872798f1f7f4baa8e1ac58976ad6972:
      title: 'The Wish-Fulfilling Tree: A Prayer to the All-Embodying Lama Tsokye
        Dorje'
      parent: Rangrik Dorje
    71c0e7cbcc3d45199de1420f1a89eb31:
      title: 'Victory Over All Adversity: A Prayer to Invoke Guru Rinpoche’s Wisdom
        for the Swift Fulfilment of Wishes'
      parent: Rangrik Dorje
    f9a3cbc97d534a7986d38d06b2bdbdf1:
      title: 'Cloud Banks of Blessings: A Prayer Recounting the Eleven Deeds of the
        Life and Liberation of the Guru from Uḍḍiyāna'
      parent: Ratna Lingpa
    6d8263bd39034e89825bd74b7bee36b7:
      title: The Invocation of Uḍḍiyāna on the Tenth Day
      parent: Ratna Lingpa
    d2fe6e247c6b48eab095cfdfb7fb315f:
      title: A Prayer To Padmasambhava
      parent: Shechen Gyaltsab Gyurme Pema Namgyal
    6fab919774a74a7587d98e641ff02d41:
      title: A Prayer to the Vajradhara of Oḍḍiyāna
      parent: Shechen Gyaltsab Gyurme Pema Namgyal
    c8beca534e28437196efa9a96aefa1ec:
      title: 'The Beat of the Vajra Drum: A Prayer'
      parent: Shechen Rabjam Rinpoche
    6d662bd397ce4fe09cea38335ea6df07:
      title: Topical Outline of the Prayer That Swiftly Fulfils All Wishes (Sampa
        Nyur Drupma)
      parent: Outlines
created_at: '2022-03-01T03:50:02.039694'
last_modified_at: '2022-03-01T03:50:02.039700'
